#!/usr/bin/python3

import sys
import os

os.chdir(sys.path[0])

# Target path
TARGET_PATH = "../src/mapdata.js"


# Get a list of all files
def getFileList(dirName):
    fileList = os.listdir(dirName)
    files = list()
    # Go through files
    for f in fileList:
        fullPath = os.path.join(dirName, f)
        if os.path.isdir(fullPath):
            files = files + getFileList(fullPath)
        else:
            files.append(fullPath)
    return files 


# Remove files with other than the given prefix
def filterFileList(files, prefix):
    ret = list()
    for f in files:
        if f[-4:] == "." + prefix:
            ret.append(f)
    return ret


# Find map content from a file
def findMapContent(path):

    f = open(path, "r")
    content = f.read()
    start = content.find("\"csv\">") +7
    end = content.find("</data>")
    f.close()

    return content[start: end]

# Target file
tf = open(TARGET_PATH, "w")
# Write header
tf.write("// Generated by mapconv.py. See dev folder.\n")
tf.write("const MAP_DATA=[")

# Get files
files = filterFileList(getFileList("maps"), "tmx")
print(files)
for f in files:
    tf.write("[")
    tf.write(findMapContent(f))
    tf.write("],")

# End
tf.write("\n];\n")

tf.close()
